# Generated by Django 5.1.3 on 2024-11-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_dir', models.CharField(max_length=50)),
            ],
        ),
    ]
