# Generated by Django 5.1 on 2024-11-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('cafe_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cafe_dir', models.CharField(max_length=50)),
                ('cafe_man', models.CharField(max_length=50)),
                ('cafe_phone', models.CharField(max_length=50)),
                ('cafe_city', models.CharField(max_length=50)),
                ('cafe_mail', models.CharField(max_length=50)),
                ('cafe_num', models.IntegerField()),
            ],
        ),
    ]
