# Generated by Django 5.1 on 2024-11-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('inventory_name', models.CharField(max_length=50)),
                ('inventory_quantity', models.IntegerField()),
                ('inventory_capacity', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
