# Generated by Django 5.1 on 2024-11-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_freq',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
